### ISSUE TITLE
Sphinx build failed

### ISSUE THREAD

**Issue by terrencetec** [terrencetec/kontrol#27]
For future readers, the solution for this problem is to pin `docutils<0.18` in your `requirements.txt` file, and have a `.readthedocs.yaml` file with these contents:

```
version: 2

python:
   install:
   - requirements: docs/requirements.txt
```

More information [in our docs](https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file).

_Originally posted by @astrojuanlu in https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858_
